-- SOUTH SIDE POS AUTO STOCK + RECIPE MAPPING
-- Jalankan di Supabase SQL Editor

alter table menus add column if not exists hpp integer not null default 0;

create table if not exists menu_recipes (
  id bigint generated by default as identity primary key,
  menu_id bigint not null,
  stock_item_id bigint not null,
  qty_per_cup numeric not null default 0,
  created_at timestamp with time zone default now()
);

alter table menu_recipes enable row level security;

drop policy if exists "allow all menu_recipes" on menu_recipes;

create policy "allow all menu_recipes"
on menu_recipes
for all
to anon
using (true)
with check (true);

alter publication supabase_realtime add table menu_recipes;
